import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faArrowRight,
  faBezierCurve,
  faClock,
  faCogs,
  faDumbbell,
  faGripLines,
  faHamburger,
  faInfoCircle,
  faLineChart,
  faList,
  faPen,
  faPersonWalking,
  faPlateWheat,
  faRobot,
  faRulerHorizontal,
  faSave,
  faSearch,
  faTimes,
  faTrophy,
  faCaretLeft,
  faCaretRight,
  faFileImport,
  faFileExport,
  faRefresh,
} from "@fortawesome/free-solid-svg-icons";

export const loadIcons = () => library.add(
  faCogs,
  faDumbbell,
  faPen,
  faPlateWheat,
  faArrowRight,
  faTrophy,
  faHamburger,
  faLineChart,
  faList,
  faDumbbell,
  faTimes,
  faGripLines,
  faBezierCurve,
  faRobot,
  faPersonWalking,
  faSearch,
  faRulerHorizontal,
  faClock,
  faInfoCircle,
  faSave,
  faCaretLeft,
  faCaretRight,
  faTrophy,
  faFileImport,
  faFileExport,
  faRefresh
);
